server.port=8081
spring.application.name=screenmatch
spring.main.banner-mode=CONSOLE
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{dd-MM-yy E HH:mm:ss.SSS}){faint} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){red} %clr(:){yellow} %clr(%m){faint}%n
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost/alura_series
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=never
spring.data.web.pageable.page-parameter=pagina
spring.data.web.pageable.size-parameter=tamanho
spring.data.web.sort.sort-parameter=ordem